Fix #35 | Upgrade WordPress Coding Standards to 3.1.0
10up/wpcs-action pull request #49
Opened 2024-07-15 09:54 UTC by sksaju

### Description of the Change

Closes https://github.com/10up/wpcs-action/issues/35

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-08-09 13:31 UTC, iamdharmesh reviewed
Hi @sksaju,

Thanks for the working on the PR. I have started testing it, but getting `/action/entrypoint.sh: line 5: composer: not found` error. Could you please help with checking it once?

You can find logs of action run here: https://github.com/iamdharmesh/autoshare-for-twitter/actions/runs/10319895557/job/28569247554?pr=5

Thank you.

2024-08-23 09:40 UTC, mehul0810 approved these changes, later dismissed
Looks good to me!

2024-09-04 01:52 UTC, benlk commented on entrypoint.sh
> +composer global require "dealerdirect/phpcodesniffer-composer-installer:^0.7.1" "wp-coding-standards/wpcs:^3.1.0"
@sksaju As noted in @iamdharmesh's run log https://github.com/iamdharmesh/autoshare-for-twitter/actions/runs/10319895557/job/28569247554?pr=5 this workflow doesn't work if `composer` isn't available.

Since this PR adds a requirement for `composer` to exist in the testrunner's `$PATH`, this PR should also:

- `set -ueo pipefail` to cause the check to fail early if `composer` is not installed
- add a note in `CHANGELOG.md` that this tool now requires `composer` in the testrunner

Alternatively:

- replace the `composer global require` with a different method of installing PHPCS and the WordPress Coding Standards

2024-09-04 13:28 UTC, jeffpaul commented on entrypoint.sh
> +composer global require "dealerdirect/phpcodesniffer-composer-installer:^0.7.1" "wp-coding-standards/wpcs:^3.1.0"
@iamdharmesh any preference on approach noted by @benlk above?

2024-09-05 11:10 UTC, iamdharmesh commented on entrypoint.sh
> +composer global require "dealerdirect/phpcodesniffer-composer-installer:^0.7.1" "wp-coding-standards/wpcs:^3.1.0"
Thanks for checking on this and sharing approaches, @benlk. @jeffpaul, the approaches shared by Ben looks good, and I would prefer handling the `composer` installation in the action itself (in the `Dockerfile`), so action users don’t have to deal with it.

2024-09-08 22:31 UTC, benlk commented on entrypoint.sh
> +composer global require "dealerdirect/phpcodesniffer-composer-installer:^0.7.1" "wp-coding-standards/wpcs:^3.1.0"
So then in https://github.com/10up/wpcs-action/blob/05677bafa9c8c199acecfe79fd464d69fd6dbf0e/Dockerfile#L11 we might add `apk add composer`

2024-09-12 18:20 UTC, sksaju commented on entrypoint.sh
> +composer global require "dealerdirect/phpcodesniffer-composer-installer:^0.7.1" "wp-coding-standards/wpcs:^3.1.0"
Thanks, @iamdharmesh @benlk, I've added the composer installation script in the PR, could you take another look, please?

2024-09-13 16:54 UTC, iamdharmesh commented on entrypoint.sh
> +composer global require "dealerdirect/phpcodesniffer-composer-installer:^0.7.1" "wp-coding-standards/wpcs:^3.1.0"
Thanks for making the changes, @sksaju. The code looks good. However, I tried running the action on the repo, and it’s still failing due to a missing required PHP extension. I didn't got the time to look into it deeply, but here are the logs: https://github.com/iamdharmesh/autoshare-for-twitter/actions/runs/10852960407/job/30120164745?pr=5

Thank you.

2024-09-18 17:02 UTC, benlk commented on entrypoint.sh
> +composer global require "dealerdirect/phpcodesniffer-composer-installer:^0.7.1" "wp-coding-standards/wpcs:^3.1.0"
In that build log, there are two notes about missing php extensions:

>     - wp-coding-standards/wpcs 3.1.0 requires ext-tokenizer * -> it is missing from your system. Install or enable PHP's tokenizer extension.

>     - squizlabs/php_codesniffer[2.0.0, ..., 2.9.2] require ext-tokenizer * -> it is missing from your system. Install or enable PHP's tokenizer extension.
>    - squizlabs/php_codesniffer[3.8.0, ..., 3.10.2] require ext-simplexml * -> it is missing from your system. Install or enable PHP's simplexml extension.
    
I expect that `ext-tokenizer` and `ext-simplexml` are available in the `apk` package repository.

Looking at the results of `apk update &&     apk upgrade &&     apk add git &&     apk add composer` earlier in that build log, it looks like we're using `php8-` on Alpine 3.16, and [in the list of packages matching that constraint](https://pkgs.alpinelinux.org/packages?name=php8-*&branch=v3.16&repo=community&arch=&maintainer=), we would use the packages `php8-simplexml` and `php8-tokenizer` 

To do:
- [ ] `apk add php8-simplexml`
- [ ] `apk add php8-tokenizer`
- [ ] since `apk add` supports multiple packages in one call according to https://wiki.alpinelinux.org/wiki/Alpine_Package_Keeper#Add_a_Package , condense the `apk add` calls to `apk add git composer php8-simplexml php8-tokenizer` and anything else that needs to be installed.
- [ ] if mere installation doesn't fix the issue, see if we need to adjust `php.ini` to enable those extensions.

2024-09-19 10:59 UTC, thrijith commented on entrypoint.sh
> +composer global require "dealerdirect/phpcodesniffer-composer-installer:^0.7.1" "wp-coding-standards/wpcs:^3.1.0"
@benlk I added the required extensions but looks like there is some other issue.

This is the latest error `ERROR: Referenced sniff "PHPCSUtils" does not exist`

but phpcsutils seems to be installed? 
https://github.com/thrijith/autoshare-for-twitter/actions/runs/10938472447/job/30369473907?pr=2#step:4:46
https://github.com/thrijith/autoshare-for-twitter/actions/runs/10938472447/job/30369473907?pr=2#step:4:40

2024-09-28 19:24 UTC, benlk commented on entrypoint.sh
> +    decide_all_files_or_changed "${HOME}/vipcs,${HOME}/variable-analysis"
```suggestion
    decide_all_files_or_changed "$(composer config home)/vendor/wp-coding-standards/wpcs,${HOME}/vipcs,${HOME}/variable-analysis"
```

This fixes the missing `WordPress.Security.EscapeOutput` mentioned at https://github.com/thrijith/autoshare-for-twitter/actions/runs/10938472447/job/30369473241?pr=2#step:4:76

2024-09-28 19:24 UTC, benlk commented on entrypoint.sh
> +  decide_all_files_or_changed "$(composer config home)/vendor/wp-coding-standards/wpcs"
```suggestion
  echo "Setting up default WPCS"
  git clone --depth 1 --branch 1.0.11 https://github.com/PHPCSStandards/PHPCSUtils ${HOME}/phpcsutils
  decide_all_files_or_changed "$(composer config home)/vendor/wp-coding-standards/wpcs,${HOME}/phpcsutils/PHPCSUtils"
```

Can we add an `echo` line inside this `elif` block to say which standard is being set up and run? That would make this match every other block within this conditional.

This block needs to have `PHPCSUtils` cloned within it, to address the error in https://github.com/thrijith/autoshare-for-twitter/actions/runs/10938472447/job/30369473907?pr=2#step:4:56

2024-09-28 19:24 UTC, benlk commented on entrypoint.sh
> +    decide_all_files_or_changed "${HOME}/10up/10up-Default,${HOME}/phpcompatwp/PHPCompatibilityWP,${HOME}/phpcompat/PHPCompatibility,${HOME}/phpcompat-paragonie/PHPCompatibilityParagonieSodiumCompat,
```suggestion
    decide_all_files_or_changed "$(composer config home)/vendor/wp-coding-standards/wpcs,${HOME}/10up/10up-Default,${HOME}/phpcompatwp/PHPCompatibilityWP,${HOME}/phpcompat/PHPCompatibility,${HOME}/phpcompat-paragonie/PHPCompatibilityParagonieSodiumCompat,${HOME}/phpcompat-paragonie/PHPCompatibilityParagonieRandomCompat,${HOME}/phpcsutils/PHPCSUtils,${HOME}/vipcs,${HOME}/variable-analysis"
```

This fixes the missing `WordPress.DB.PreparedSQL` in https://github.com/thrijith/autoshare-for-twitter/actions/runs/10938472447/job/30369473560?pr=2#step:4:82

2024-09-28 19:24 UTC, benlk commented on entrypoint.sh
> +composer global require "dealerdirect/phpcodesniffer-composer-installer:^0.7.1" "wp-coding-standards/wpcs:^3.1.0"
Installed, but not in `installed_paths` for some reason. If we explicitly set `installed_paths`, does the `composer`-installed standard's automatic registration with PHPCS get overridden? I'll make another comment with the needed changes.

2024-09-28 19:25 UTC, benlk requested changes
Ensure that the composer-installed WPCS is available to all standards, and add PHPCSUtils to the default WPCS run.

2024-10-04 11:04 UTC, thrijith commented
@benlk I made some changes but it seems to be failing https://github.com/thrijith/autoshare-for-twitter/actions/runs/10938472447/job/31076394106?pr=2#step:4:87

The error is `ERROR: Referenced sniff "Generic.CodeAnalysis.RequireExplicitBooleanOperatorPrecedence"` which was added 3.9.0 https://github.com/PHPCSStandards/PHP_CodeSniffer/discussions/343, but we are installing 3.10.3 already https://github.com/thrijith/autoshare-for-twitter/actions/runs/10938472447/job/31076394106?pr=2#step:4:25 so not sure why that would be an issue.

2024-11-06 19:13 UTC, s3rgiosan requested changes

2024-11-06 19:13 UTC, s3rgiosan commented on entrypoint.sh
> +  decide_all_files_or_changed "$(composer config home)/vendor/wp-coding-standards/wpcs,${HOME}/phpcsutils/PHPCSUtils"
Hi @sksaju, when using the default standard, I'm getting `ERROR: Referenced sniff "Universal.NamingConventions.NoReservedKeywordParameterNames" does not exist`. This occurs because PHPCSExtra's path isn't included in PHPCS's `installed_paths` configuration, even though it's installed globally via composer.

I think we need to add PHPCSExtra's path to the `decide_all_files_or_changed` call:

```
decide_all_files_or_changed "$(composer config home)/vendor/wp-coding-standards/wpcs,${HOME}/phpcsutils/PHPCSUtils,$(composer config home)/vendor/phpcsstandards/phpcsextra"
```

cc @benlk @jeffpaul

2024-11-06 19:13 UTC, s3rgiosan commented on entrypoint.sh
> +    decide_all_files_or_changed "$(composer config home)/vendor/wp-coding-standards/wpcs,${HOME}/vipcs,${HOME}/variable-analysis"
Hi @sksaju, when using the WordPress-VIP-Go standard, I'm getting `ERROR: Referenced sniff "WordPress.PHP.StrictComparisons" does not exist`. This occurs because the action is missing the PHPCSUtils path in its configuration.

I think we need to add PHPCSUtils to the `decide_all_files_or_changed` paths:

```
decide_all_files_or_changed "$(composer config home)/vendor/wp-coding-standards/wpcs,${HOME}/vipcs,${HOME}/variable-analysis,${HOME}/phpcsutils/PHPCSUtils"
```

cc @benlk @jeffpaul

2024-11-06 19:13 UTC, s3rgiosan commented on entrypoint.sh
> +    decide_all_files_or_changed "$(composer config home)/vendor/wp-coding-standards/wpcs,${HOME}/10up/10up-Default,${HOME}/phpcompatwp/PHPCompatibilityWP,${HOME}/phpcompat/PHPCompatibility,${HOME}/ph
Hi @sksaju, when using the 10up-Default standard, I'm getting `ERROR: Referenced sniff "Generic.CodeAnalysis.RequireExplicitBooleanOperatorPrecedence" does not exist`. Since this sniff is included in PHP_CodeSniffer core, the error is unexpected.

Could we add `phpcs -i` to the action output to see which standards are actually installed? This could help debug the issue.

cc @benlk @jeffpaul

2024-11-24 19:47 UTC, sksaju commented on entrypoint.sh
> +    decide_all_files_or_changed "$(composer config home)/vendor/wp-coding-standards/wpcs,${HOME}/vipcs,${HOME}/variable-analysis"
@s3rgiosan I've updated the PR, could you take another look, please? Thank you

2025-01-14 03:26 UTC, jeffpaul commented
@10up/open-source-practice would be great to get some help on final review, testing, and updates here and then merged and released to take advantage of the 3.x standards

2025-05-12 07:07 UTC, iamdharmesh commented
**Update:**

I have updated the Dockerfile to use the PHP 8 Alpine image and installed PHPCS and Composer on top of it. The image we were previously extending was using an older version of PHPCS (3.7.2), which was a blocker for this upgrade. After the changes to the Docker image, it started working as expected. However, PHPCS check for using the local config is not working properly, likely due to a path issue. I will look into it and fix it to make this ready for merge and release. Thanks!

2025-05-12 12:31 UTC, Sidsector9 commented
@iamdharmesh try passing the `phpcs -vv` flag to log which ruleset file it is using.

2025-05-29 14:31 UTC, iamdharmesh commented
@jeffpaul We’re all set to proceed here. Just wanted to get a second set of eyes on this PR for a quick review before merging. Thanks!

cc: @dkotter @sudar

2025-05-29 17:12 UTC, dkotter approved these changes

2025-05-29 17:43 UTC, s3rgiosan approved these changes

2025-05-29 21:05 UTC, jeffpaul commented
@benlk any further concerns from your end on merging/releasing here?

2025-06-10 17:03 UTC, benlk commented
No comments from me.

2025-07-03 13:44 UTC, iamdharmesh commented
@dkotter I’m unable to merge this as merging is blocked. Could you please help with merging it so we can proceed with the release next week? Thanks!

2025-07-03 14:09 UTC, merged